# Generated by Django 3.2.5 on 2021-08-03 20:05

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_date', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), books.models.max_value_current_year])),
                ('number_of_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_link', models.URLField(blank=True, max_length=500, null=True)),
                ('isbn_number', models.CharField(blank=True, max_length=13, null=True, unique=True, validators=[books.models.validate_isbn_number_length, books.models.validate_isbn_control_number])),
                ('language', models.CharField(blank=True, help_text='Language should be written as two-letter abbreviation', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookSearcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('from_date', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), books.models.max_value_current_year])),
                ('to_date', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), books.models.max_value_current_year])),
                ('language', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyValueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=20)),
            ],
        ),
    ]
