# Generated by Django 3.2.5 on 2021-08-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210731_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, help_text='Language should be written as two-letter abbreviation', max_length=2, null=True),
        ),
    ]
