# Generated by Django 3.2.5 on 2021-08-03 17:03

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[books.models.validate_isbn_number_length, books.models.validate_isbn_control_number]),
        ),
    ]
